project_id = "dbooubfdjxfuubxaqdme"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[functions.elevenlabs-token]
verify_jwt = false

[functions.ai-conversation]
verify_jwt = false

[functions.run-tests]
verify_jwt = false
